sb = ['reminder_cnt_1d', 'reminder_cnt_1w', 'interrupt_cnt_1d', 'interrupt_cnt_1w', 'ban_reason_abnormal', 
'income_number', 'income_number_pct', 'income_cnt', 'outcome_number', 'outcome_number_pct', 'outcome_cnt',
 'income_face_2_face_pct', 'outcome_face_2_face_pct', 'income_max_pattern_pct', 'outcome_max_pattern_pct',
  'income_max_pattern_cnt', 'outcome_max_pattern_cnt', 'income_number_rate', 'outcome_number_rate',
   'income_abnormal', 'outcome_abnormal', 'trans_per_acc', 'trans_total_number', 'trans_account_number', 
   'trans_account_pct', 'pic_per_acc', 'pic_total_number', 'pic_account_number', 'pic_account_pct', 'gamble_in_evidence', 
   'gamble_account_nummber', 'cashback_in_evidence', 'cashback_account_number', 'cashout_in_evidence', 'cashout_account_number', 
   'exchange_in_evidence', 'exchange_account_number', 'porn_in_evidence', 'porn_account_number', 'alipay_cnt', 
   'alipay_account_number', 'gamble_proof_account', 'gamble_in_proof', 'porn_proof_account', 'porn_in_proof', 
   'pull_back_proof_account', 'pull_back_in_proof', 'reporter_money_cnt', 'reporter_money_pct', 
   'be_reported_money_cnt', 'be_reported_money_pct', 'complaint_account_number', 'from_complaint_account_number', 
   'complaint_number', 'complaint_sens_pct', 'spread_trans_per_acc', 'spread_trans_total_number', 'spread_trans_account_number',
    'spread_trans_account_pct', 'spread_pic_per_acc', 'spread_pic_total_number', 'spread_pic_account_number', 
    'spread_pic_account_pct', 'spread_gamble_in_evidence', 'spread_gamble_account_nummber', 'spread_cashback_in_evidence', 
    'spread_cashback_account_number', 'spread_cashout_in_evidence', 'spread_cashout_account_number', 
    'spread_exchange_in_evidence', 'spread_exchange_account_number', 'spread_porn_in_evidence', 
    'spread_porn_account_number', 'spread_alipay_cnt', 'spread_alipay_account_number', 'spread_gamble_proof_account',
     'spread_gamble_in_proof', 'spread_porn_proof_account', 'spread_porn_in_proof', 'spread_pull_back_proof_account',
      'spread_pull_back_in_proof', 'spread_reporter_money_cnt', 'spread_reporter_money_pct', 'spread_be_reported_money_cnt',
       'spread_be_reported_money_pct', 'spread_complaint_account_number', 'spead_from_complaint_account_number', 
       'spread_complaint_number', 'spread_complaint_sens_pct', 'spread_all_acc_cnt', 'same_device_account_number', 
       'same_idcard_account_number', 'qun_repeat', 'qun_similarity_cos', 'qun_abnormal', 'wxpay_register_time',
        'iphone_pct', 'android_pct', 'windows_pct', 'ipad_pct', 'mac_pct', 'change_device_cnt', 'opentime_to_now', 
        'sale_in_wxp', 'business_in_wxp', 'illegal_solicit_in_wxp', 'gamble_in_wxp', 'gamble_pattern_in_wxp', 
        'nickname', 'signature', 'age', 'account_nickname_similarity', 'deviceblockrate', 'deviceexposerate', 
        'cardblockrate', 'cardexposerate'
